### ISSUE TITLE
Are you aware of ansible/ansible-kubernetes-modules?

### ISSUE THREAD

**Issue by LorbusChris** [appuio/ansible-module-openshift#2]
Hi everyone,

I was wondering if you are aware of [ansible-kubernetes-modules](https://github.com/ansible/ansible-kubernetes-modules). It is used in [Ansible Playbook Bundles](https://github.com/ansibleplaybookbundle/ansible-playbook-bundle) for provisioning resources.
In that setup, one registers an APB at the [Ansible Service Broker](https://github.com/openshift/ansible-service-broker) and then can use the [Service Catalog](https://github.com/kubernetes-incubator/service-catalog) to provision it.

I reckon this here might be a similar use case and thought you might want to get rid of this repo's maintanance overhead if there is a valid alternative in the longer run.

Please feel free to close this issue.

PS: More specifically it is this module that I thought you might be able to use: https://github.com/ansible/ansible-kubernetes-modules/blob/master/library/openshift_v1_template.py

**Comment by dtschan** [comment]
Hi Chris

Thank you for your information. I've looked at the Ansible k8s modules some time ago but they didn't do what we needed then. I'll look at them again. Now there's also lib_openshift which has some overlap: https://github.com/openshift/openshift-ansible/tree/master/roles/lib_openshift/library

We'll mainly use our modules to manage cluster configuration not covered by the OpenShift Ansible playbook and to manage infrastructure components like Gluster recycler or HAProxy customizations. So the most important aspect is that the cluster is not touched if there are no configuration changes. Even a write operation that doesn't change anything can trigger deployments or builds.
The documentation of the openshift_v1_template indicates that this is not always idempotent. Do you have some more information in which cases it is not idempotent?

Kind regards
  Daniel

**Comment by LorbusChris** [comment]
Hi Daniel,
sorry for not following up on this earlier.
I am not sure about the idempotency of the k8s modules, although I believe they're meant to be.
Thank you for pointing out lib_openshift to me!

Kind regards
Chris
